import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { GeistPixelTriangle } from "geist/font/pixel";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Footer } from "@/components/shared/Footer";
import { Panel } from "@/components/shared/Panel";
import { Header } from "@/components/shared/Header";
import Separator from "@/components/shared/Separator";
import { Toaster } from "sileo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark overflow-x-hidden w-full">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${GeistPixelTriangle.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-0 z-50 bg-background border-b w-full">
            <Panel className="max-w-4xl mx-auto">
              <Header />
            </Panel>
          </div>
          <div className="max-w-4xl mx-auto min-h-screen">
            {children}
            <Toaster position="bottom-right" />
            <Panel>
              <Footer />
            </Panel>
            <Separator />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
